parameters:
  salt:
    master:
      environment:
        prd:
          formula:
            heka:
              source: pkg
              name: salt-formula-heka
            elasticsearch:
              source: pkg
              name: salt-formula-elasticsearch
            influxdb:
              source: pkg
              name: salt-formula-influxdb
            kibana:
              source: pkg
              name: salt-formula-kibana
            java:
              source: pkg
              name: salt-formula-java

