parameters:
  _param:
    jenkins_security_matrix_admins:
      # Full admin access
      - akomarek
      - fpytloun
      - jenkins-mk
      - jjosef
      - jpavlik
      - mceloud
      - tkukral
      - chnyda
      - jbroulik
      - mpolreich
      - mmosesohn
      - ikharin
      - vsaienko
      - ovoshchana
      - mkarpin
    jenkins_security_matrix_read:
      # Read only access
      - anonymous
      - fuel-qa-team-eng
      - mirantis
      - mirantis-mcp-ci-eng
      - mosqa-eng
      - opencontrail-eng
      - qa-eng
    jenkins_security_matrix_build:
      # Read + permissions to build jobs
      - fuel-qa-team-eng
      - mirantis
      - mirantis-mcp-ci-eng
      - mosqa-eng
      - opencontrail-eng
      - qa-eng
    jenkins_security_matrix_write:
      # Build permissions + create/delete, whatever.
      - fuel-qa-team-eng
      - mirantis-mcp-ci-eng
      - mosqa-eng
      - opencontrail-eng
      - qa-eng
      - obourdon
  jenkins:
    client:
      security:
        matrix:
          permissions:
            Jenkins:
              ADMINISTER: ${_param:jenkins_security_matrix_admins}
              READ: ${_param:jenkins_security_matrix_read}
            hudson:
              model:
                Item:
                  BUILD: ${_param:jenkins_security_matrix_build}
                  CANCEL: ${_param:jenkins_security_matrix_build}
                  CONFIGURE: ${_param:jenkins_security_matrix_write}
                  CREATE: ${_param:jenkins_security_matrix_write}
                  DELETE: ${_param:jenkins_security_matrix_write}
                  DISCOVER: ${_param:jenkins_security_matrix_build}
                  EXTENDED_READ: ${_param:jenkins_security_matrix_build}
                  WIPEOUT: ${_param:jenkins_security_matrix_write}
                  WORKSPACE: ${_param:jenkins_security_matrix_write}
                  READ: ${_param:jenkins_security_matrix_read}
                Run:
                  DELETE: ${_param:jenkins_security_matrix_write}
                  ARTIFACTS: ${_param:jenkins_security_matrix_write}
                  UPDATE: ${_param:jenkins_security_matrix_write}
                View:
                  READ: ${_param:jenkins_security_matrix_read}
            com:
              sonyericsson:
                hudson:
                  plugins:
                    gerrit:
                      trigger:
                        PluginImpl:
                          RETRIGGER: ${_param:jenkins_security_matrix_build}
