classes:
  - cluster.mk_ci_prd
  - system.salt.master.pkg
  - system.salt.master.api
  - system.reclass.storage.salt
#  - system.sphinx.server.doc.reclass
#  - system_extra.openssh.client.salt
parameters:
  _param:
    reclass_data_repository: https://github.com/anascko/jenkins-qa.git
    reclass_data_revision: master
    reclass_config_master: ${_param:salt_master_host}
    salt_master_base_environment: prd
